server:
  port: 8080
  servlet:
    context-path: /report
spring:
  application:
    name: "Microservice-reports"
  devtools:
    add-properties: false
  profiles:
    include: null
aws:
  region: "us-east-2"
  dynamodb:
    endpoint: "${ENDPOINT_DYNAMO}"
    accessKey: "${AWS_ACCESS_KEY_ID}"
    secretKey: "${AWS_SECRET_ACCESS_KEY}"
entrypoint:
  sqs:
    approved:
      region: "us-east-2"
      queueUrl: "${AWS_URL_SQS_APPROVED}"
      waitTimeSeconds: 10
      visibilityTimeoutSeconds: 30
      maxNumberOfMessages: 10
      numberOfThreads: 1
    daily:
      region: "us-east-2"
      queueUrl: "${AWS_URL_SQS_REPORT}"
      waitTimeSeconds: 10
      visibilityTimeoutSeconds: 30
      maxNumberOfMessages: 10
      numberOfThreads: 1
management:
  endpoints:
    web:
      base-path: /report/actuator
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
security:
  jwt:
    expiration: 3600000
    public-key-location: "${JWT_PUBLIC_KEY}"
ses:
  email:
    admin: "${EMAIL_ADMIN}"
    ses: "${EMAIL_SES}"